icatproject/ids.server

src/main/java/org/icatproject/ids/thread/DfWriter.java
The DfWriter does not close the InputStream it gets from the mainStorageInterface.  As a result, the glassfish process keeps all files copied by the DfWriter into archive storage open.
=> Fix file leak in DfWriter

src/test/java/org/icatproject/ids/integration/one/FileCheckerTest.java, src/test/java/org/icatproject/ids/integration/two/FileCheckerTest.java, src/test/java/org/icatproject/ids/integration/twodf/FileCheckerTest.java
As discussed in the monthly meeting, I was able to run the test suite in the first place.  But I got errors from running the tests:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
[...]
Running org.icatproject.ids.integration.two.FileCheckerTest
Setting up two.properties took 0.021seconds
About to wait
/hmi/payara41/glassfish/domains/domain1/data/ids/archive/284/575 will be truncated to 300
Watching /hmi/payara41/glassfish/domains/domain1/data/ids/errorLog
Watching /hmi/payara41/glassfish/domains/domain1/data/ids/errorLog
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 39.377 sec <<< FAILURE! - in org.icatproject.ids.integration.two.FileCheckerTest …
```
=> Fix FileCheckerTest: wrong character index reading error log.

src/main/java/org/icatproject/ids/Transmitter.java, src/site/xhtml/release-notes.xhtml
=> Create the JMS session in a try-with-resources statement in the Transmitter

src/main/config/run.properties.example, src/main/java/org/icatproject/ids/FiniteStateMachine.java, src/main/java/org/icatproject/ids/PropertyHandler.java, src/main/scripts/setup, src/site/xhtml/installation.xhtml.vm, src/site/xhtml/release-notes.xhtml, src/test/resources/two.properties, src/test/resources/twodf.properties
Add new configuration properties `delayDatasetWritesSeconds` and `delayDatafileOperationsSeconds`, replacing `writeDelaySeconds`.  To ensure compatibility with existing configurations, `writeDelaySeconds` will be used if either is not set.  But this use is deprecated.  Fix #94.
=> Add configuration properties delayDatasetWritesSeconds and delayDatafileOperationsSeconds

src/main/java/org/icatproject/ids/thread/DsRestorer.java, src/site/xhtml/release-notes.xhtml, src/test/java/org/icatproject/ids/integration/two/RestoreErrorsTest.java
Make `DsRestorer` correctly deal with errors caused by corrupt archive files. This adds checks for:
+ spurious entries in the archive file, e.g. entries that have no corresponding datafile in the dataset.
+ duplicate entries in the archive file.
+ missing entries in the archive file.
In all cases, an error is thrown, which will abort the restorer and cause a failure to be recorded for the dataset.  Fix #96.
=> Review error handling in DsRestorer

src/main/java/org/icatproject/ids/IdsBean.java
Remove the check for pending deferred operations when checking whether the data selection is online in the write call. This fixes #101.
=> Do not check pending deferred operations in the write call

src/main/config/run.properties.example, src/main/java/org/icatproject/ids/IdsBean.java, src/main/java/org/icatproject/ids/IdsService.java, src/main/java/org/icatproject/ids/PropertyHandler.java, src/site/xhtml/installation.xhtml.vm, src/site/xhtml/release-notes.xhtml
Add a new optional configuration flag `enableWrite` to enable or disable the `write` call.
Fix #105.
This PR does not fix the odd behavior of `archive`, `restore`, and `write` to do nothing and silently succeed with single level storage.  Apparently this has been considered a feature at least once. The removal of that feature should not be hidden in an unrelated bug fix, even if it may be questionable.
=> Add a configuration option enableWrite to enable or disable the write call

src/main/java/org/icatproject/ids/IdsBean.java, src/main/java/org/icatproject/ids/IdsService.java, src/site/xhtml/release-notes.xhtml, src/test/java/org/icatproject/ids/integration/one/GetDataExplicitTest.java, src/test/java/org/icatproject/ids/integration/one/GetStatusExplicitTest.java, src/test/java/org/icatproject/ids/integration/two/GetDataExplicitTest.java, src/test/java/org/icatproject/ids/integration/two/GetStatusExplicitTest.java, src/test/java/org/icatproject/ids/integration/twodf/GetDataExplicitTest.java, src/test/java/org/icatproject/ids/integration/twodf/GetStatusExplicitTest.java, src/test/java/org/icatproject/ids/integration/util/client/TestingClient.java
This is the straightforward implementation of variations of `getStatus()` and `getSize()` that accaept a `preparedID` rather then `investigationIds`, `datasetIds`, and `datafileIds`.  It implements and closes #104.
=> Extend getStatus and getSize to accept a preparedID

src/main/java/org/icatproject/ids/IdsBean.java, src/main/java/org/icatproject/ids/IdsService.java, src/site/xhtml/release-notes.xhtml, src/test/java/org/icatproject/ids/integration/one/MiscTest.java, src/test/java/org/icatproject/ids/integration/one/WriteTest.java
The calls archive, restore, and write are meaningless for an IDS configured as single level storage.  In the current version, these calls silently do nothing, successfully.  This PR changes this behavior, the calls now throw `NotImplementedException` instead.
This may be considered a somewhat artificial problem.  But it may be confusing if a call returns success while nothing happens.  it is considered a better behavior to send a clear message.
=> Throw NotImplementedException for meaningless calls in single level storage

pom.xml, src/site/xhtml/release-notes.xhtml
Bump the dependency on `icat.utils` to 4.16.1 (released on 2021-02-11).  This adds Python 3 compatibility for the `setup` script.
=> Bump icat.utils to 4.16.1

.github/workflows/ci-build.yml, README.md, README.txt
Adds CI using GitHub Actions and a status badge to the README. The status badge will start working once this PR gets merged into `master`, but this is the status badge for this branch to prove that it works:
[![Build Status](https://github.com/icatproject/ids.server/workflows/CI%20Build/badge.svg?branch=127-add-ci)](https://github.com/icatproject/ids.server/actions?query=workflow%3A%22CI+Build%22)
closes #127
=> Add CI using GitHub Actions

src/main/scripts/setup, src/site/xhtml/release-notes.xhtml, src/test/scripts/prepare_test.py
Modern distros often don't have a `python` command, so use `python3` explicitly.
=> Use python3 instead of python

src/test/scripts/prepare_test.py
The preparation script for the integration tests `prepare_test.py` sets up the install directory `src/test/install` to install `ids.server` from there to the Payara server, creating all the needed files. While doing that, it blindly overwrite existing files. This is intended in the case of `run.properties`, because the integration tests need to be run for different deployment scenarios that need to be configured in `run.properties`. But it is bad in the case of `setup.properties` and `logback.xml`, because they may need to be manually adapted to the test environment.
The present PR changes the behavior of the script to not overwrite existing `setup.properties` or `logback.xml`. In the default case, starting from an empty `src/test/install` directory, this makes no difference. But it is …
=> Do not overwrite setup.properties or logback.xml in the test install directory

.github/workflows/ci-build.yml
The build for Java 8 and for Java 11 cannot succeed both at the same time: as long as we have the `miredot-plugin` at version 1.6.2, the build for Java 11 will  inevitably fail, as soon as we upgrade it, the build for Java 8 will inevitably fail. So it's kind of pointless trying to build for both versions at the same time in the CI build. I'd rather suggest to build only for the Java version that has a chance to succeed, e.g. to exclude the build for Java 11 for the moment and to include the switch from Java 8 to Java 11 in the [payara6](https://github.com/icatproject/ids.server/tree/payara6) branch. This will also get rid of the annoying red x mark for commits that were actually tested successful in the CI, as ac513e0.
=> Exclude Java 11 from CI build for the time being

src/test/java/org/icatproject/ids/integration/one/FileCheckerTest.java, src/test/java/org/icatproject/ids/integration/two/FileCheckerTest.java
Drop the test case for file size null in `org.icatproject.ids.integration.one.FileCheckerTest.everythingTest` and `org.icatproject.ids.integration.two.FileCheckerTest.everythingTest` respectively: this error condition can not be reproduced any more with `icat.server` 5.0 and newer: `Datafile.fileSize` has now a default value of 0, so there is no way any more to set it to `null`. The check for a wrong numeric value in `fileSize` is already covered in the previous test case respectively, so there is no point in keeping that test case at all.
Close #129.
=> Drop the test case for file size null in FileCheckerTest

miredot.htmlintro.html, pom.xml, src/main/config/run.properties.example, src/main/java/org/icatproject/ids/FileChecker.java, src/main/java/org/icatproject/ids/IdsBean.java, src/main/java/org/icatproject/ids/IdsService.java, src/main/java/org/icatproject/ids/PropertyHandler.java, src/main/scripts/setup, src/site/xhtml/installation.xhtml.vm, src/site/xhtml/release-notes.xhtml, src/test/java/org/icatproject/ids/integration/BaseTest.java, src/test/java/org/icatproject/ids/integration/one/BaseTests.java, src/test/java/org/icatproject/ids/integration/two/BaseTests.java, src/test/java/org/icatproject/ids/integration/twodf/BaseTests.java, src/test/java/org/icatproject/ids/integration/util/client/TestingClient.java
Remove deprecated features:
- Remove `getApiVersion` call, deprecated in 1.8.0,
- Remove runtime property `writeDelaySeconds`, deprecated in 1.10.0.
Deprecate the `FileChecker` and the `getLink` API call. Both features are slated for definitive removal in version 3.0.
- Issue a warning in the `setup` script if either is enabled in `run.properties`,
- Log a warning during initialization if the `FileChecker` is enabled,
- Log a warning when the `getLink` call is invoked, if it is enabled.
=> Remove deprecated features and deprecate FileChecker and getLink call

.github/workflows/ci-build.yml, pom.xml, src/main/java/org/icatproject/ids/CORSResponseFilter.java, src/main/java/org/icatproject/ids/DataSelection.java, src/main/java/org/icatproject/ids/FileChecker.java, src/main/java/org/icatproject/ids/FiniteStateMachine.java, src/main/java/org/icatproject/ids/ICATGetter.java, src/main/java/org/icatproject/ids/IcatReader.java, src/main/java/org/icatproject/ids/IdsBean.java, src/main/java/org/icatproject/ids/IdsService.java, src/main/java/org/icatproject/ids/LockManager.java, src/main/java/org/icatproject/ids/PropertyHandler.java, src/main/java/org/icatproject/ids/Tidier.java, src/main/java/org/icatproject/ids/Transmitter.java, src/main/java/org/icatproject/ids/exceptions/IdsExceptionMapper.java, src/main/java/org/icatproject/ids/exceptions/NotFoundExceptionMapper.java, src/main/java/org/icatproject/ids/exceptions/RuntimeExceptionMapper.java, src/main/scripts/setup, src/main/webapp/WEB-INF/web.xml, src/site/xhtml/release-notes.xhtml, src/test/java/org/icatproject/ids/DataSelectionDevTest.java, src/test/java/org/icatproject/ids/integration/BaseTest.java, src/test/java/org/icatproject/ids/integration/util/client/TestingClient.java, src/test/scripts/prepare_test.py
The key changes in this PR are:
- Imports of JavaEE classes in the `javax` namespace are changed to the `jakarta` namespace.
- The Java version in increases to Java 11 since this is the minimum supported by JakartaEE.
- The dependency on commons-fileupload is removed since there is no version compatible with the jakarta namespace. The native multipart handling in the Servlet API is used instead.
The first 2 changes are not backwards-compatible so this is a new major version.
=> Upgrade to JakartaEE 10 API for compatibility with Payara 6

src/main/scripts/setup
Fixup #139: the properties `filesCheck.parallelCount` and `linkLifetimeSeconds` in `run.properties` have been changed from mandatory to optional (even deprecated actually). But this change has not been properly reflected in the `setup` script that still throws an error if they are not set.
=> Fix setup script: filesCheck.parallelCount and linkLifetimeSeconds are optional

.github/workflows/ci-build.yml
Switch back using the master branch from icatproject-contrib/icat-ansible after icatproject-contrib/icat-ansible#84 has been merged.
=> Use master from icatproject-contrib/icat-ansible rather than payara6

src/main/java/org/icatproject/ids/DataSelection.java, src/main/java/org/icatproject/ids/IdsBean.java
Motivation:
The 'Content-Length' response header is expected by many clients.  While it is not possible to specify the content length for on-the-fly compression, it is possible when sending an individual file.
Modification:
Update DataSelection to optionally return the content length.
Update the 'getData' Response to include the `Content-Length` header when the request targets a single file that is not placed in a zip archive.  If the content is dynamically generated (e.g., a zip file) then no `Content-Length` header is provided.
Result:
IDS now includes the `Content-Length` response header when this is possible
=> Include Content-Length response header

src/main/java/org/icatproject/ids/LockManager.java, src/site/xhtml/release-notes.xhtml
- store the storage lock in class LockEntry rather than in class SingleLock,
- as a consequence: obtain only one storage lock when mutliple shared locks are requested on the same dataset,
- release the storage lock when the lock count drops to zero, e.g. when the last lock on the dataset is closed.
This fixes #164.
=> Fix duplicate calls of mainStorage.lock() in LockManager
